// Anthony Galczak - agalczak@cnm.edu
// Java I - Program 4 GUI by NetBeans
// JFrameGUI.java - The GUI / Frame

package galczakp4;

import java.awt.Font;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony
 */
public class JFrameGUI extends javax.swing.JFrame {

    Data data;
    /**
     * Creates new form JFrameGUI
     */
    public JFrameGUI() {
        // Displaying the course header
        JOptionPane.showMessageDialog(null, 
                "Anthony Galczak - agalczak@cnm.edu\nJava I - Program 4 GUI by NetBeans", 
                "CIS 2235 - GalczakP4", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
        data = new Data();
        
        // Initializing the label that describes the memory slider
        data.setMemoryIndex(jsldMemory.getValue());
        jlblMemory.setText(data.getMemory());
        jlblPrice.setText(String.valueOf(data.getMemoryPrice()));
    }

    public void captureData(){
        // Setting name, computer name, color into data class
        data.setName(jtxtName.getText());
        data.setcName(jtxtComputerName.getText());
        data.setColor(jcboxColor.getSelectedItem().toString());
        
        // Setting processor into data class via radio buttons
        if(jradProc1.isSelected()){
            data.setProcessor(jradProc1.getText());
        }
        else if(jradProc2.isSelected()){
            data.setProcessor(jradProc2.getText());
        }
        else if(jradProc3.isSelected()){
            data.setProcessor(jradProc3.getText());
        }
        
        // Setting HDD into data class via radio buttons
        if(jradHDD1.isSelected()){
            data.setHDD(jradHDD1.getText());
        }
        else if(jradHDD2.isSelected()){
            data.setHDD(jradHDD2.getText());
        }
        else if(jradHDD3.isSelected()){
            data.setHDD(jradHDD3.getText());
        }
        
        // Setting periphs into data class via check boxes
        if (jckboxPeripheral1.isSelected()){
            data.setPeriphs(jckboxPeripheral1.getText());
        }
        if (jckboxPeripheral2.isSelected()){
            data.setPeriphs(jckboxPeripheral2.getText());
        }
        if (jckboxPeripheral3.isSelected()){
            data.setPeriphs(jckboxPeripheral3.getText());
        }
      
        
        

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpProcessors = new javax.swing.ButtonGroup();
        btnGrpHDDs = new javax.swing.ButtonGroup();
        jcboxColor = new javax.swing.JComboBox();
        jbtSummary = new javax.swing.JButton();
        jbtSave = new javax.swing.JButton();
        jtxtName = new javax.swing.JTextField();
        jtxtComputerName = new javax.swing.JTextField();
        jradProc1 = new javax.swing.JRadioButton();
        jradProc2 = new javax.swing.JRadioButton();
        jradProc3 = new javax.swing.JRadioButton();
        jradHDD1 = new javax.swing.JRadioButton();
        jradHDD2 = new javax.swing.JRadioButton();
        jradHDD3 = new javax.swing.JRadioButton();
        jsldMemory = new javax.swing.JSlider();
        jckboxPeripheral1 = new javax.swing.JCheckBox();
        jckboxPeripheral2 = new javax.swing.JCheckBox();
        jckboxPeripheral3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaResults = new javax.swing.JTextArea();
        jlblMemory = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcboxColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blue", "Black", "Orange", "Translucent" }));

        jbtSummary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtSummary.setText("Summary");
        jbtSummary.setMaximumSize(new java.awt.Dimension(100, 25));
        jbtSummary.setMinimumSize(new java.awt.Dimension(100, 25));
        jbtSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtSummaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtSummaryMouseExited(evt);
            }
        });
        jbtSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSummaryActionPerformed(evt);
            }
        });

        jbtSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtSave.setText("Save");
        jbtSave.setMaximumSize(new java.awt.Dimension(100, 25));
        jbtSave.setMinimumSize(new java.awt.Dimension(100, 25));
        jbtSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtSaveMouseExited(evt);
            }
        });
        jbtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveActionPerformed(evt);
            }
        });

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        btnGrpProcessors.add(jradProc1);
        jradProc1.setSelected(true);
        jradProc1.setText("i3 6100 - $150");

        btnGrpProcessors.add(jradProc2);
        jradProc2.setText("i7 6700K - $400");

        btnGrpProcessors.add(jradProc3);
        jradProc3.setText("AMD FX 5950 - $300");
        jradProc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradProc3ActionPerformed(evt);
            }
        });

        btnGrpHDDs.add(jradHDD1);
        jradHDD1.setSelected(true);
        jradHDD1.setText("1TB HDD - $50");

        btnGrpHDDs.add(jradHDD2);
        jradHDD2.setText("256GB SSD - $120");

        btnGrpHDDs.add(jradHDD3);
        jradHDD3.setText("1TB SSD - $200");

        jsldMemory.setMajorTickSpacing(1);
        jsldMemory.setMaximum(2);
        jsldMemory.setPaintLabels(true);
        jsldMemory.setPaintTicks(true);
        jsldMemory.setSnapToTicks(true);
        jsldMemory.setToolTipText("Memory Selection");
        jsldMemory.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldMemoryStateChanged(evt);
            }
        });

        jckboxPeripheral1.setText("Gaming Mouse - $100");

        jckboxPeripheral2.setText("Gaming Keyboard - $200");

        jckboxPeripheral3.setText("Gaming Headphones - $250");

        jLabel1.setText("Processors");

        jLabel2.setText("Hard Drives");

        jLabel3.setText("Peripherals");

        jLabel4.setText("Color of Computer");

        jLabel5.setText("Computer Name");

        jLabel6.setText("Your Name");

        jLabel7.setText("<html><center>Welcome to Anthony's Computer Store.<br> Enter your name and the name you want etched on your computer's case.<br> Select your Processor, Hard Drive, and Peripherals.<br> Then select your amount of Memory.<br> Review the price and select Save.<br></center></html>");

        jtaResults.setColumns(20);
        jtaResults.setRows(5);
        jScrollPane1.setViewportView(jtaResults);

        jlblMemory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblMemory.setText("Memory Size");

        jLabel8.setText("Memory Slider");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("<html>Memory<br>Price</html>");

        jlblPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblPrice.setText("p");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jradProc1)
                            .addComponent(jradProc2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradHDD1)
                                .addGap(40, 40, 40)
                                .addComponent(jckboxPeripheral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradHDD3)
                                .addGap(36, 36, 36)
                                .addComponent(jckboxPeripheral3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradHDD2)
                                .addGap(22, 22, 22)
                                .addComponent(jckboxPeripheral2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jradProc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addComponent(jtxtName))
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtComputerName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jcboxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlblMemory))
                                        .addComponent(jsldMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlblPrice)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtComputerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradHDD1)
                    .addComponent(jradProc1)
                    .addComponent(jckboxPeripheral1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradHDD2)
                    .addComponent(jradProc2)
                    .addComponent(jckboxPeripheral2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradProc3)
                    .addComponent(jradHDD3)
                    .addComponent(jckboxPeripheral3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsldMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblMemory)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPrice))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jradProc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradProc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradProc3ActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jbtSummaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSummaryMouseEntered
        jbtSummary.setFont(new Font("Tahoma", Font.BOLD, 16));
    }//GEN-LAST:event_jbtSummaryMouseEntered

    private void jbtSummaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSummaryMouseExited
        jbtSummary.setFont(new Font("Tahoma", Font.PLAIN,12));
    }//GEN-LAST:event_jbtSummaryMouseExited

    private void jbtSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSaveMouseEntered
        jbtSave.setFont(new Font("Tahoma", Font.BOLD, 16));
    }//GEN-LAST:event_jbtSaveMouseEntered

    private void jbtSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSaveMouseExited
        jbtSave.setFont(new Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_jbtSaveMouseExited

    private void jbtSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSummaryActionPerformed
        captureData();
        // Outputting the summary string/toString
        jtaResults.setText(data.toString());
    }//GEN-LAST:event_jbtSummaryActionPerformed

    private void jsldMemoryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldMemoryStateChanged
        data.setMemoryIndex(jsldMemory.getValue());
        jlblMemory.setText(data.getMemory());
        jlblPrice.setText(String.valueOf(data.getMemoryPrice()));
    }//GEN-LAST:event_jsldMemoryStateChanged

    private void jbtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveActionPerformed
        // Capturing the data off from the frame
        captureData();
        
        // Opening a new dialog for the user to write the file
        JFileChooser fileChooser = new JFileChooser();
        int iSaveOrCancel = fileChooser.showSaveDialog(this);
        if(iSaveOrCancel == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            data.writeFile(file);
        }
    }//GEN-LAST:event_jbtSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpHDDs;
    private javax.swing.ButtonGroup btnGrpProcessors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtSave;
    private javax.swing.JButton jbtSummary;
    private javax.swing.JComboBox jcboxColor;
    private javax.swing.JCheckBox jckboxPeripheral1;
    private javax.swing.JCheckBox jckboxPeripheral2;
    private javax.swing.JCheckBox jckboxPeripheral3;
    private javax.swing.JLabel jlblMemory;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JRadioButton jradHDD1;
    private javax.swing.JRadioButton jradHDD2;
    private javax.swing.JRadioButton jradHDD3;
    private javax.swing.JRadioButton jradProc1;
    private javax.swing.JRadioButton jradProc2;
    private javax.swing.JRadioButton jradProc3;
    private javax.swing.JSlider jsldMemory;
    private javax.swing.JTextArea jtaResults;
    private javax.swing.JTextField jtxtComputerName;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
