# -*- coding: utf-8 -*-
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

penta_nums = [1, 5, 12, 22, 35, 51, 70, 92, 117, 145]

for x in range(11, 10000):
    penta_num = (x-1)*(3*(x-1)-1)/2

    penta_nums.append(penta_num)


for num1 in penta_nums:
    for num2 in penta_nums:
        if num2 - num1 in penta_nums and num2 + num1 in penta_nums:
            print "num1:%d num2:%d" % (num1, num2)

# TODO: Really slow

